exp_name: exp30
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PointEnv() # GymEnv('Reacher-v1', record_video=False)
  n_rollouts: 2000000
  train_every_n_rollouts: 4000
  n_envs: 8
  exploration_strategy:
    type: gaussian
    gaussian:
      max_sigma: 0.5
      min_sigma: 0.01
  render: False
  is_async: False

##############
### Policy ###
##############

policy:
  H: 1

  # architecture
  type: mlp # mlp / rnn
  mlp:
    hidden_layers: [40, 40]
    activation: tf.nn.relu
  rnn:
    obs_hidden_layers: [20]
    action_hidden_layers: [20]
    reward_hidden_layers: [10, 5]
    rnn_state_dim: 20
    activation: tf.nn.relu

  # training
  train_steps: 5000
  weight_decay: 0.
  learning_rate: 0.001
  batch_size: 16
  reset_every_train: True

  # device
  gpu_device: 0
  gpu_frac: 0.2

########################
### Action selection ###
########################

get_action:
  type: random # random / lattice

  random:
    type: random
    N: 1000
  lattice:
    type: lattice
    N: 10
