exp_name: exp321
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: GymEnv('Swimmer-v1', record_video=False)
  n_envs: 5

  total_steps: 1000000 # 1e6
  learn_after_n_steps: 2000 # 2e3 
  train_every_n_steps: 5
  save_every_n_steps: 200000 # 2e5
  update_target_after_n_steps: 4000 # 4e3
  update_target_every_n_steps: 2000 # 2e3
  update_preprocess_every_n_steps: 500
  log_every_n_steps: 5000 # 5e3

  exploration_strategy:
    type: gaussian
    gaussian:
      max_sigma: 0.5
      min_sigma: 0.01
      decay_period: 500000 # 5e5
    epsilon_greedy:
      epsilon: 1
      decay_func: 'lambda t: int(t < 500)'

  batch_size: 16
  replay_pool_size: 1000000 # 1e6
  render: False

##############
### Policy ###
##############

policy:
  H: 5
  gamma: 0.5

  # architecture
  type: rnn # mlp / rnn
  mlp:
    hidden_layers: [20, 20, 20]
    activation: tf.nn.tanh
  rnn:
    obs_hidden_layers: [20]
    action_hidden_layers: [20]
    reward_hidden_layers: [20, 20]
    rnn_state_dim: 20
    activation: tf.nn.tanh

  # training
  weight_decay: 0.0001
  learning_rate: 0.01

  # device
  gpu_device: 0
  gpu_frac: 0.2

########################
### Action selection ###
########################

get_action:
  type: random # random / lattice

  random:
    type: random
    N: 1000
  lattice:
    type: lattice
    N: 10
