exp_name: exp32
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PointEnv() # GymEnv('Reacher-v1', record_video=False)
  n_envs: 5

  total_steps: 100000 # 1e5
  learn_after_n_steps: 100
  train_every_n_steps: 20
  save_every_n_steps: 10000
  update_target_every_n_steps: 100
  log_every_n_steps: 200

  exploration_strategy:
    type: gaussian
    gaussian:
      max_sigma: 0.5
      min_sigma: 0.01

  batch_size: 16
  replay_pool_size: 1000000 # 1e6
  render: False

##############
### Policy ###
##############

policy:
  H: 1

  # architecture
  type: mlp # mlp / rnn
  mlp:
    hidden_layers: [40, 40]
    activation: tf.nn.relu
  rnn:
    obs_hidden_layers: [20]
    action_hidden_layers: [20]
    reward_hidden_layers: [10, 5]
    rnn_state_dim: 20
    activation: tf.nn.relu

  # training
  weight_decay: 0.
  learning_rate: 0.001

  # device
  gpu_device: 1
  gpu_frac: 0.2

########################
### Action selection ###
########################

get_action:
  type: random # random / lattice

  random:
    type: random
    N: 1000
  lattice:
    type: lattice
    N: 10
