exp_name: exp475
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: GymEnv('CartPole-v0', record_video=False)
  n_envs: 5

  total_steps: 100000 # 1e5
  learn_after_n_steps: 500 # 500 
  train_every_n_steps: 5
  save_every_n_steps: 20000 # 2e4
  update_target_after_n_steps: 1000
  update_target_every_n_steps: 100
  update_preprocess_every_n_steps: 100 # 100
  log_every_n_steps: 500

  exploration_strategy:
    type: epsilon_greedy
    gaussian:
      max_sigma: 0.5
      min_sigma: 0.01
      decay_period: 500000 # 5e5
    epsilon_greedy:
      epsilon: 1
      decay_func: 'lambda t: max(0.5*(1-t/1e4), 0.01)'

  batch_size: 32
  replay_pool_size: 100000 # 1e5
  save_rollouts: True
  render: False

##############
### Policy ###
##############

policy:
  H: 1
  gamma: 0.9

  # architecture
  type: discrete_mlp # mlp / discrete_mlp / rnn
  mlp:
    hidden_layers: [20, 20, 20]
    activation: tf.nn.tanh
  discrete_mlp:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh  
  rnn:
    obs_hidden_layers: [20]
    action_hidden_layers: [20]
    reward_hidden_layers: [20, 20]
    rnn_state_dim: 20
    activation: tf.nn.tanh

  # training
  weight_decay: 0
  learning_rate: 0.0001
  grad_clip_norm: 100000

  # device
  gpu_device: 0
  gpu_frac: 0.4

########################
### Action selection ###
########################

get_action:
  type: lattice # random / lattice

  random:
    type: random
    N: 1000
  lattice:
    type: lattice
    N: 10
