exp_name: exp43
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: ChainEnv(10)
  n_envs: 1

  total_steps: 5000 # 5e3
  learn_after_n_steps: 500
  train_every_n_steps: 5
  save_every_n_steps: 2500
  update_target_after_n_steps: 1000
  update_target_every_n_steps: 500
  update_preprocess_every_n_steps: 100
  log_every_n_steps: 10

  exploration_strategy:
    type: epsilon_greedy
    gaussian:
      max_sigma: 0.5
      min_sigma: 0.01
    epsilon_greedy:
      epsilon: 1
      decay_func: 'lambda t: int(t < 500)'

  batch_size: 16
  replay_pool_size: 100000 # 1e5
  render: False

##############
### Policy ###
##############

policy:
  H: 4
  gamma: 1

  # architecture
  type: mlp # mlp / rnn
  mlp:
    hidden_layers: [20, 20, 20]
    activation: tf.nn.tanh
  rnn:
    obs_hidden_layers: [20]
    action_hidden_layers: [20]
    reward_hidden_layers: [10, 5]
    rnn_state_dim: 20
    activation: tf.nn.relu

  # training
  weight_decay: 0.
  learning_rate: 0.001

  # device
  gpu_device: 0
  gpu_frac: 0.2

########################
### Action selection ###
########################

get_action:
  type: lattice # random / lattice

  random:
    type: random
    N: 1000
  lattice:
    type: lattice
    N: 10
