exp_name: exp699
exp_prefix: rnn_critic
seed: 5

#################
### Algorithm ###
#################

alg:
  env: GymEnv('Reacher-v1', record_video=False)
  n_envs: 4

  total_steps: 1.e+6
  learn_after_n_steps: 1.e+4
  train_every_n_steps: 4
  save_every_n_steps: 2.e+5
  update_target_after_n_steps: 1.e+4
  update_target_every_n_steps: 1.e+3
  update_preprocess_every_n_steps: 1.e+8
  log_every_n_steps: 1.e+3

  exploration_strategy:
    class: GaussianStrategy
    GaussianStrategy:
      endpoints: [[0, 0.01], [1.e+6, 0.01]]
      outside_value: 0.01
    EpsilonGreedyStrategy:
      endpoints: [[0, 1.0], [5.e+4, 1.0], [1.e+6, 0.1], [5.e+6, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: True
  render: False

##############
### Policy ###
##############

policy:
  N: 3
  H: 3
  cost_type: combined # combined / separated
  gamma: 0.9
  obs_history_len: 1

  class: MultiactionCombinedcostRNNPolicy
  DQNPolicy:
    hidden_layers: [256, 256]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  DiscreteDQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  NstepDQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostMLPPolicy:
    hidden_layers: [256, 256]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostRNNPolicy:
    obs_hidden_layers: [32,32]
    action_hidden_layers: [16,16]
    reward_hidden_layers: [16,16]
    rnn_state_dim: 32
    use_lstm: True
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu
  MultiactionSeparatedcostMLPPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
  MultiactionSeparatedcostRNNPolicy:
    obs_hidden_layers: [128]
    action_hidden_layers: [128]
    reward_hidden_layers: [128]
    value_hidden_layers: [128]
    rnn_state_dim: 128
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu

  # preprocessing
  preprocess:
    observations_mean: False
    observations_orth: False
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 0
  lr_schedule:
    endpoints: [[0, 1.e-4], [1.e+6, 1.e-4]]
    outside_value: 1.e-4
  grad_clip_norm: 10

  # device
  gpu_device: 1
  gpu_frac: 0.4

########################
### Action selection ###
########################

get_action:
  type: random # random / lattice

  random:
    type: random
    K: 1000
  lattice:
    type: lattice
    K: 10
