exp_name: exp667
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PremadeGymEnv(wrap_deepmind(gym.envs.make('PongNoFrameskip-v3')), record_video=False, record_log=False)
  n_envs: 1

  total_steps: 8.e+6
  learn_after_n_steps: 5.e+4
  train_every_n_steps: 4
  save_every_n_steps: 5.e+5
  update_target_after_n_steps: 1.e+4
  update_target_every_n_steps: 1.e+4
  update_preprocess_every_n_steps: 1.e+4
  log_every_n_steps: 1.e+4

  exploration_strategy:
    class: EpsilonGreedyStrategy
    GaussianStrategy:
      max_sigma: 0.5
      min_sigma: 0.01
      decay_period: 5.e+5 # 5e5
    EpsilonGreedyStrategy:
      endpoints: [[0, 1.0], [5.e+4, 1.0], [1.e+6, 0.1], [5.e+6, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: False
  render: False

##############
### Policy ###
##############

policy:
  N: 1
  H: 1
  cost_type: combined # combined / separated
  gamma: 0.99
  obs_history_len: 4

  class: DQNPolicy
  DQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    concat_or_bilinear: bilinear
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  DiscreteDQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  NstepDQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostMLPPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostRNNPolicy:
    obs_hidden_layers: [128]
    action_hidden_layers: [128]
    reward_hidden_layers: [128]
    rnn_state_dim: 128
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu
  MultiactionSeparatedcostMLPPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
  MultiactionSeparatedcostRNNPolicy:
    obs_hidden_layers: [128]
    action_hidden_layers: [128]
    reward_hidden_layers: [128]
    value_hidden_layers: [128]
    rnn_state_dim: 128
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu


  # training
  weight_decay: 0
  lr_schedule:
    endpoints: [[0, 1.e-4], [1.e+6, 1.e-4], [5.e+6, 5.e-5]]
    outside_value: 5.e-5
  grad_clip_norm: 10

  # device
  gpu_device: 0
  gpu_frac: 0.4

########################
### Action selection ###
########################

get_action:
  type: lattice # random / lattice

  random:
    type: random
    K: 1000
  lattice:
    type: lattice
    K: 10
