exp_name: exp728
exp_prefix: rnn_critic
seed: 4

#################
### Algorithm ###
#################

alg:
  env: GymEnv('CartPole-v0', record_video=False)
  n_envs: 5

  total_steps: 1.e+5
  learn_after_n_steps: 500
  train_every_n_steps: 5
  save_every_n_steps: 2.e+4
  update_target_after_n_steps: 1.e+3
  update_target_every_n_steps: 1.e+2
  update_preprocess_every_n_steps: 1.e+8
  log_every_n_steps: 1000

  exploration_strategy:
    class: EpsilonGreedyStrategy
    GaussianStrategy:
      endpoints: [[0, 0.01], [1.e+6, 0.01]]
      outside_value: 0.01
    EpsilonGreedyStrategy:
      endpoints: [[0, 1.0], [500, 0.5], [1.e+4, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: True
  render: False

##############
### Policy ###
##############

policy:
  N: 6
  H: 1
  cost_type: combined # combined / separated
  gamma: 0.9
  obs_history_len: 1

  class: NstepDQNPolicy
  DQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  DiscreteDQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  NstepDQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostMLPPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionCombinedcostRNNPolicy:
    obs_hidden_layers: [20,20]
    action_hidden_layers: [20,20]
    reward_hidden_layers: [20,20]
    rnn_state_dim: 32
    use_lstm: True
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu
  MultiactionSeparatedcostMLPPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
    concat_or_bilinear: bilinear
  MultiactionSeparatedcostRNNPolicy:
    obs_hidden_layers: [20,20]
    action_hidden_layers: [20,20]
    reward_hidden_layers: [20,20]
    rnn_state_dim: 32
    use_lstm: True
    activation: tf.nn.tanh
    rnn_activation: tf.nn.relu

  # preprocessing
  preprocess:
    observations_mean: False
    observations_orth: False
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 0
  lr_schedule:
    endpoints: [[0, 1.e-3], [1.e+6, 1.e-3]]
    outside_value: 1.e-3
  grad_clip_norm: 10

  # device
  gpu_device: 0
  gpu_frac: 0.1

########################
### Action selection ###
########################

get_action:
  type: lattice # random / lattice

  random:
    type: random
    K: 1000
  lattice:
    type: lattice
    K: 10
