exp_name: phd037
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PhdEnv(length=3, r_continue=-1, r_escape=0, r_thesis=600)
  n_envs: 4
  
  total_steps: 2.e+5
  sample_after_n_steps: -1
  learn_after_n_steps: 5.e+4
  train_every_n_steps: 4
  eval_every_n_steps: 1.e+2
  save_every_n_steps: 2.e+4
  update_target_after_n_steps: 1.e+3
  update_target_every_n_steps: 1.e+3
  update_preprocess_every_n_steps: 1.e+3
  log_every_n_steps: 1.e+3

  exploration_strategy:
    class: EpsilonGreedyStrategy
    EpsilonGreedyStrategy:
      endpoints: [[0, 1], [5.e+4, 1]]
      outside_value: 1
    
  batch_size: 32
  replay_pool_size: 2.e+5
  save_rollouts: False
  save_rollouts_observations: True
  render: False

##############
### Policy ###
##############

policy:
  N: 1
  H: 1
  gamma: 0.99
  obs_history_len: 1

  values_softmax: mean # mean / final / learned
  use_target: True
  separate_target_params: True
  
  get_action_test:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 1000
    lattice:
      
  get_action_target:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 100
    lattice:

  class: MACMuxPolicy
  MACPolicy:
    obs_hidden_layers: [64]
    action_hidden_layers: [16]
    reward_hidden_layers: [16]
    value_hidden_layers: [16]
    lambda_hidden_layers: [16]
    rnn_state_dim: 64
    use_lstm: False
    activation: tf.nn.tanh
    rnn_activation: tf.nn.tanh
  MACMuxPolicy:
    obs_hidden_layers: [64]
    reward_hidden_layers: [16, 8]
    value_hidden_layers: [16, 8]
    lambda_hidden_layers: []
    rnn_state_dim: 32
    use_lstm: False
    activation: tf.nn.tanh
    rnn_activation: tf.nn.tanh

  # preprocessing
  preprocess:
    observations_mean: False
    observations_orth: False
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 1.e-7
  lr_schedule:
    endpoints: [[0, 1.e-4], [1.e+6, 1.e-4]]
    outside_value: 1.e-4
  grad_clip_norm: 10

  # device
  gpu_device: 1
  gpu_frac: 0.4


