exp_name: phd301
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PhdEnv(length=8, r_continue=-1, r_escape=0, r_adviser=-15, r_thesis=15)
  n_envs: 1
  
  offpolicy: /home/gkahn/code/rllab/data/local/rnn-critic/phd270
  num_offpolicy: 5.e+5
  
  total_steps: 5.e+5
  sample_after_n_steps: 1.e+8
  learn_after_n_steps: -1
  train_every_n_steps: 1
  eval_every_n_steps: 1.e+2
  save_every_n_steps: 5.e+4
  update_target_after_n_steps: 1.e+4
  update_target_every_n_steps: 1.e+4
  update_preprocess_every_n_steps: 1.e+3
  log_every_n_steps: 1.e+3

  exploration_strategy:
    class: EpsilonGreedyStrategy
    EpsilonGreedyStrategy:
      endpoints: [[0, 1], [5.e+4, 1]]
      outside_value: 1
    
  batch_size: 32
  replay_pool_size: 5.e+5
  save_rollouts: True
  save_rollouts_observations: True
  render: False

##############
### Policy ###
##############

policy:
  N: 1
  H: 1
  gamma: 0.99
  obs_history_len: 1

  values_softmax: mean # mean / final / learned
  retrace_lambda: 
  use_target: False
  separate_target_params: True
  
  get_action_test:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 1000
    lattice:
      
  get_action_target:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 100
    lattice:

  class: MACMuxPolicy
  DQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
  MACMuxPolicy:
    obs_hidden_layers: [128]
    reward_hidden_layers: []
    value_hidden_layers: []
    lambda_hidden_layers: []
    rnn_state_dim: 128
    use_lstm: False
    activation: tf.nn.tanh
    rnn_activation: tf.nn.tanh

  # preprocessing
  preprocess:
    observations_mean: False
    observations_orth: False
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 1.e-7
  lr_schedule:
    endpoints: [[0, 1.e-3], [1.e+6, 1.e-3]]
    outside_value: 1.e-3
  grad_clip_norm: 10

  # device
  gpu_device: 6
  gpu_frac: 0.2


