exp_name: pong116
exp_prefix: rnn_critic
seed: 2

#################
### Algorithm ###
#################

alg:
  env: PremadeGymEnv(wrap_deepmind(gym.envs.make('PongNoFrameskip-v3')), record_video=False, record_log=False)
  n_envs: 1
  
  offpolicy: /home/gkahn/code/rllab/data/local/rnn-critic/pong100
  num_offpolicy: 1.e+5
  
  total_steps: 4.e+6
  sample_after_n_steps: 1.e+8
  onpolicy_after_n_steps: 1.e+8
  learn_after_n_steps: -1
  train_every_n_steps: 4
  eval_every_n_steps: 1.e+4
  save_every_n_steps: 2.e+5
  update_target_after_n_steps: 5.e+4
  update_target_every_n_steps: 1.e+4
  update_preprocess_every_n_steps: 1.e+4
  log_every_n_steps: 1.e+4

  exploration_strategy:
    class: EpsilonGreedyStrategy
    EpsilonGreedyStrategy:
      endpoints: [[0, 1.0], [5.e+4, 1.0], [1.e+6, 0.1], [5.e+6, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: True
  save_rollouts_observations: False
  render: False

##############
### Policy ###
##############

policy:
  N: 5
  H: 5
  gamma: 0.99
  obs_history_len: 4

  values_softmax: mean # mean / final / learned
  use_target: True
  separate_target_params: True
  
  get_action_test:
    H: 5
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 10000
    lattice:
      
  get_action_target:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 100
    lattice:

  class: MACMuxPolicy
  MACMuxPolicy:
    obs_hidden_layers: [512]
    reward_hidden_layers: [16]
    value_hidden_layers: [16]
    lambda_hidden_layers: [16]
    rnn_state_dim: 32
    use_lstm: False
    activation: tf.nn.relu
    rnn_activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  DQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu

  # preprocessing
  preprocess:
    observations_mean: True
    observations_orth: True
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 1.e-8
  lr_schedule:
    endpoints: [[0, 1.e-4], [1.e+6, 1.e-4], [5.e+6, 5.e-5]]
    outside_value: 5.e-5
  grad_clip_norm: 10

  # device
  gpu_device: 6
  gpu_frac: 0.3


