exp_name: swingup046
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: CartPoleSwingupEnv(x_threshold=10, x_threshold_reward=-5000)
  max_path_length: 200
  n_envs: 4
  
  total_steps: 2.e+5
  sample_after_n_steps: -1
  learn_after_n_steps: 5.e+4
  train_every_n_steps: 4
  eval_every_n_steps: 1.e+3
  save_every_n_steps: 5.e+4
  update_target_after_n_steps: 1.e+3
  update_target_every_n_steps: 1.e+3
  update_preprocess_every_n_steps: 1.e+3
  log_every_n_steps: 1.e+4

  exploration_strategy:
    class: EpsilonGreedyStrategy
    EpsilonGreedyStrategy:
      endpoints: [[0, 1], [2.e+5, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: True
  save_rollouts_observations: True
  save_eval_rollouts_observations: True
  render: False

##############
### Policy ###
##############

policy:
  N: 10
  H: 10
  gamma: 0.99
  obs_history_len: 1

  values_softmax: mean # mean / final / learned
  use_target: True
  separate_target_params: True
  
  get_action_test:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 10000
    lattice:
      
  get_action_target:
    H: 1
    values_softmax: mean # mean / final / learned
    type: lattice # random / lattice
    random:
      K: 100
    lattice:

  class: MACMuxPolicy
  DQNPolicy:
    hidden_layers: [128, 128]
    activation: tf.nn.tanh
  MACMuxPolicy:
    obs_hidden_layers: [128]
    reward_hidden_layers: []
    value_hidden_layers: []
    lambda_hidden_layers: []
    rnn_state_dim: 128
    use_lstm: False
    activation: tf.nn.tanh
    rnn_activation: tf.nn.tanh

  # preprocessing
  preprocess:
    observations_mean: False
    observations_orth: False
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 1.e-7
  lr_schedule:
    endpoints: [[0, 1.e-3], [1.e+6, 1.e-3]]
    outside_value: 1.e-3
  grad_clip_norm: 10

  # device
  gpu_device: 0
  gpu_frac: 0.35


