exp_name: test_pong_pytorch
exp_prefix: rnn_critic
seed: 1

#################
### Algorithm ###
#################

alg:
  env: PremadeGymEnv(wrap_deepmind(gym.envs.make('PongNoFrameskip-v3')), record_video=False, record_log=False)
  n_envs: 1
  
  total_steps: 2.e+6
  learn_after_n_steps: 100 # 5.e+4
  train_every_n_steps: 4
  save_every_n_steps: 2.e+5
  update_target_after_n_steps: 5.e+4
  update_target_every_n_steps: 1.e+4
  update_preprocess_every_n_steps: 1.e+4
  log_every_n_steps: 1.e+2

  exploration_strategy:
    class: EpsilonGreedyStrategy
    GaussianStrategy:
      endpoints: [[0, 0.01], [1.e+6, 0.01]]
      outside_value: 0.01
    EpsilonGreedyStrategy:
      endpoints: [[0, 1.0], [5.e+4, 1.0], [1.e+6, 0.1], [5.e+6, 0.01]]
      outside_value: 0.01
    
  batch_size: 32
  replay_pool_size: 1.e+6
  save_rollouts: True
  save_rollouts_observations: False
  render: False

##############
### Policy ###
##############

policy:
  N: 10
  H: 10
  gamma: 0.99
  obs_history_len: 4

  use_target: True
  separate_target_params: True
  
  values_softmax_policy: mean # mean / final / learned
  values_softmax_target: mean # mean / final / learned
  
  get_action_policy:
    H: 10
    values_softmax: mean # mean / final / learned
    type: random # random / lattice
    random:
      K: 1000
    lattice:
      
  get_action_target:
    H: 10
    values_softmax: mean # mean / final / learned
    type: random # random / lattice
    random:
      K: 100
    lattice:

  class: MACPolicyPytorch
  MACPolicyPytorch:
    obs_hidden_layers: [512]
    action_hidden_layers: [16]
    reward_hidden_layers: [16]
    value_hidden_layers: [16]
    values_softmax_hidden_layers: [16]
    rnn_state_dim: 32
    use_lstm: True  # if Discrete, will use Mux
    activation: F.relu
    rnn_activation: F.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: F.relu
  MACPolicy:
    obs_hidden_layers: [512]
    action_hidden_layers: [16]
    reward_hidden_layers: [16]
    value_hidden_layers: [16]
    lambda_hidden_layers: [16]
    rnn_state_dim: 128
    use_lstm: True
    activation: tf.nn.relu
    rnn_activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  MACMuxPolicy:
    obs_hidden_layers: [512]
    reward_hidden_layers: [16]
    value_hidden_layers: [16]
    lambda_hidden_layers: [16]
    rnn_state_dim: 32
    use_lstm: True
    activation: tf.nn.relu
    rnn_activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu
  DQNPolicy:
    hidden_layers: [512]
    activation: tf.nn.relu
    conv_hidden_layers: [32, 64, 64]
    conv_kernels: [8, 4, 3]
    conv_strides: [4, 2, 1]
    conv_activation: tf.nn.relu

  # preprocessing
  preprocess:
    observations_mean: True
    observations_orth: True
    actions_mean: False
    actions_orth: False
    rewards_mean: False
    rewards_orth: False

  # training
  weight_decay: 1.e-8
  lr_schedule:
    endpoints: [[0, 1.e-4], [1.e+6, 1.e-4], [5.e+6, 5.e-5]]
    outside_value: 5.e-5
  grad_clip_norm: 10

  # device
  gpu_device: 0
  gpu_frac: 0.8


